# Generated by Django 6.0.4 on 2026-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskill',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
